#!/bin/sh
# Regenerate gdl.dict, a libFuzzer dictionary of GDL tokens, from the kernel's
# X-macro .def files.  Keywords and property/type/table names steer the fuzzer
# into real GDL syntax quickly.  Run from anywhere; pass the source root as $1
# (default: two levels up from this script).
#
# Xconq is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.

set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
srcroot=${1:-$(CDPATH= cd -- "$here/../.." && pwd)}
kernel="$srcroot/kernel"
out="$here/gdl.dict"

{
    echo "# GDL token dictionary for libFuzzer, generated by gen_dict.sh."
    echo "# Do not edit by hand; regenerate from kernel/*.def."
    echo
    # First string-literal argument of every DEF_* macro across the .def files
    # that name GDL-visible symbols: keywords, and the type/property/table/
    # variable/action/task names.  These are exactly the tokens the reader and
    # interpreter match against.
    for f in keyword.def utype.def mtype.def ttype.def gvar.def \
             table.def action.def task.def plan.def goal.def cmd.def; do
        [ -f "$kernel/$f" ] || continue
        # Pull the first "quoted" argument out of each DEF_*(...) line.
        sed -n 's/^[[:space:]]*DEF_[A-Z_]*("\([^"]*\)".*/\1/p' "$kernel/$f"
    done | LC_ALL=C sort -u | while IFS= read -r sym; do
        # Skip empty tokens; escape backslashes and quotes for dict syntax.
        [ -n "$sym" ] || continue
        esc=$(printf '%s' "$sym" | sed 's/\\/\\\\/g; s/"/\\"/g')
        printf '"%s"\n' "$esc"
    done
    # A few structural tokens the .def files don't spell out as symbols.
    printf '%s\n' '"("' '")"' '"\""' '"|"' '";"' '"#|"' '"|#"' \
                  '"1d6"' '"3d6+2"' '"\\041"' '"0x"' '"-"' '"."'
} > "$out"

echo "wrote $out ($(grep -c '^"' "$out") tokens)"
