"xtconq*portholeLabel.Translations: #override \\n\
	~Shift<Btn1Down>: toolaction() \\n\
	 Shift<Btn1Down>: toolselection() \\n\
	~Shift<Btn2Down>: select() movelook() \\n\
	 Shift<Btn2Down>: select() \\n\
	 Shift<Btn2Up>:   distance() \\n\
	<Btn3Down>: select() moveunit() \\n\
	Meta<MotionNotify>:motionselect() movelook() \\n\
	<KeyPress>KP_7: movelook_ul() \\n\
	<KeyPress>KP_4: movelook_l() \\n\
	<KeyPress>KP_1: movelook_dl() \\n\
	<KeyPress>KP_9: movelook_ur() \\n\
	<KeyPress>KP_6: movelook_r() \\n\
	<KeyPress>KP_3: movelook_dr() \\n\
	<KeyPress>KP_5: center() \\n\
	<Expose>:   redraw() \\n\
	<KeyPress>: keypress() \\n",
"xtconq*map*helpPop.label:		help",
"xtconq*map*controlForm*top:			ChainTop",
"xtconq*map*controlForm*bottom:		ChainTop",
"xtconq*map*sides.top:			ChainTop",
"xtconq*map*sides.bottom:			ChainTop",
"xtconq*map*sides.left:			ChainLeft",
"xtconq*map*sides.right:			ChainLeft",
"xtconq*map*listView.top:			ChainTop",
"xtconq*map*listView.bottom:		ChainBottom",
"xtconq*map*listView.left:		ChainLeft",
"xtconq*map*listView.right:		ChainLeft",
"xtconq*map*panner.top:			ChainBottom",
"xtconq*map*panner.bottom:		ChainBottom",
"xtconq*map*panner.left:			ChainLeft",
"xtconq*map*panner.right:			ChainLeft",
"xtconq*map*panner.rubberBand:		true",
"xtconq*helpShell.title:			xtconq help",
"xtconq*helpShell*topicPort.height:	300",
"xtconq*helpShell*topicPort.width:	100",
"xtconq*helpShell*title.width:		500",
"xtconq*helpShell*title.borderWidth:	  0",
"xtconq*helpShell*title.font:		-*-helvetica-bold-r-*-*-18-*-*-*-*-*-*-*",
"xtconq*helpShell*text.height:		300",
"xtconq*helpShell*text.width:		400",
"xtconq*helpShell*topicList.font:		-*-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*helpShell*text*font:		7x13",
"xtconq*PrintSetup.title:			xtconq print setup",
"xtconq*PrintSetup*Dialog*value:		0",
"xtconq*PrintSetup*Dialog*value.translations: #override \\n\
	<Key>Return: DoPrintDialog()",
"xtconq*PrintSetup*help.Label:		\\ help ",
"xtconq*PrintSetup*print.Label:		\\ print ",
"xtconq*PrintSetup*done.Label:		\\ done ",
"xtconq*PrintSetup*names.label:		interesting names",
"xtconq*PrintSetup*cellSize.label:	cell size",
"xtconq*PrintSetup*gridSize.label:	grid thick.",
"xtconq*PrintSetup*pageWidth.label:	page width",
"xtconq*PrintSetup*pageHeight.label:	page height",
"xtconq*PrintSetup*topMargin.label:	top margin",
"xtconq*PrintSetup*bottomMargin.label:	bottom margin",
"xtconq*PrintSetup*leftMargin.label:	left margin",
"xtconq*PrintSetup*rightMargin.label:	right margin",
"xtconq*PrintSetup*terrainGray.label:	terrain gray",
"xtconq*PrintSetup*enemyGray.label:	enemy gray",
"xtconq*PrintSetup*borderWidth.label:	border thick.",
"xtconq*PrintSetup*connWidth.label:	conn thick.",
"xtconq*PrintSetupHelp.title:		xtconq print setup help",
"xtconq*PrintSetupHelp*baseTranslations: #override \
	<Key>Return: DonePrintHelp() \\n\
	<Key>Escape: DonePrintHelp() ",
"xtconq*PrintSetupHelp*helpDone.Label: \\ done ",
"xtconq*map*ctrlpanelPop.label:		contr. panel",
"xtconq*ctrlpanelPop*top:			ChainTop",
"xtconq*ctrlpanelPop*bottom:		ChainTop",
"xtconq*ctrlpanelPop*left:		ChainLeft",
"xtconq*ctrlpanelPop*right:		ChainLeft",
"xtconq*controlPanel.title: xtconq control panel",
"xtconq*controlPanel.form.popDown.label:	close",
"xtconq*controlPanel.form.what.label: what should I draw in the map window?",
"xtconq*controlPanel.form.monochrome.label: should I use black&white?",
"xtconq*controlPanel.form.color.label: what should I use color images for?",
"xtconq*controlPanel.form.what.vertDistance:	 4",
"xtconq*controlPanel.form.Label.vertDistance:	12",
"xtconq*controlPanel.form.Command.vertDistance:	12",
"xtconq*gameDialog*font:		-adobe-helvetica-medium-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameDialog*Command.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameDialog*label.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameDialog*name.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameDialog*name.width:		100",
"xtconq*gameDialog*viewport.height:	604",
"xtconq*gameDialog*label.label:		select a game",
"xtconq*gameDialog.title: 		xtconq game selection",
"xtconq.gameDialog*inForm.Form.horizDistance:	0",
"xtconq.gameDialog*inForm.Form*vertDistance:	0",
"xtconq.gameDialog*inForm.Form.borderWidth:	0",
"xtconq.gameDialog*inForm.intro.vertDistance:	4",
"xtconq*gameForm*font:		-adobe-helvetica-medium-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameForm*name.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameForm*instructions_label.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameForm*notes_label.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameForm*variant.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameForm*assign.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameForm.Command.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameForm.Dialog.value*font:-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameForm*add.label:		add player",
"xtconq*gameForm.pane*Text.width:		500",
"xtconq*gameForm.pane*Text.height:		50",
"xtconq*gameForm.pane*Text.scrollHorizontal:	whenNeeded",
"xtconq*gameForm.pane*Text.scrollVertical:	whenNeeded",
"xtconq*gameForm.pane.borderWidth:		0",
"xtconq*gameForm.pane.horizDistance:	0",
"xtconq*gameForm.varMessage.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameForm.nameMessage.font:-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*gameForm.idMessage.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*Scrollbar.Thickness:		10",
"xtconq*Scrollbar.thumb:			None",
"xtconq*ok.label:				\\ OK\\ ",
"xtconq*cancel.label:			Cancel",
"xtconq.unitCloseup*info.width:  		500",
"xtconq.unitCloseup*info.height: 		300",
"xtconq.unitCloseup*info*font:		7x13",
"xtconq.unitCloseup*icon.height:		20",
"xtconq.unitCloseup*label.height:		20",
"xtconq.unitCloseup*flag.height:		20",
"xtconq.unitCloseup*side.height:		20",
"xtconq.unitCloseup*Label.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.unitCloseup*Command.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.unitCloseup*update.label:		Update",
"xtconq.unitCloseup*focus.label:		Focus",
"xtconq.unitCloseup*close.label:		Close",
"xtconq.sideCloseup*info.width:  			500",
"xtconq.sideCloseup*info.height:	 		150",
"xtconq.sideCloseup*info*font:			7x13",
"xtconq.sideCloseup*flag.height:			20",
"xtconq.sideCloseup*side.height:			20",
"xtconq.sideCloseup*Label.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.sideCloseup*Command.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.sideCloseup*update.label:			Update",
"xtconq.sideCloseup*close.label:			Close",
"xtconq.sideCloseup*filter.width: 		500",
"xtconq.sideCloseup*filter.Toggle.height:		20",
"xtconq.sideCloseup*filter.Label.height:		20",
"xtconq.sideCloseup*filter.label.label:		Filter units:",
"xtconq.sideCloseup*filter.allTypes.label:	all types",
"xtconq.sideCloseup*filter.acpLeft.label:		ACP left",
"xtconq.sideCloseup*listUnits.label:		list units",
"xtconq.unitList*Label.height:			20",
"xtconq.unitList*allTypes.label:			all types",
"xtconq.unitList*acpLeft.label:			ACP left",
"xtconq.unitList*failed.label:			\
no unit found matching filter criteria",
"xtconq.unitList*list.forceColumns:		true",
"xtconq.unitList*list.defaultColumns:		1",
"xtconq.unitList*port.height:			300",
"xtconq.unitList*port.width:			550",
"xtconq.unitList*Label.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.unitList*Command.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.closeupList.title:			xtconq closeup list",
"xtconq.closeupList.iconName:			xtconq closeup list",
"xtconq.closeupList*list.forceColumns:		true",
"xtconq.closeupList*list.defaultColumns:		1",
"xtconq.closeupList*port.height:			300",
"xtconq.closeupList*port.width:			550",
"xtconq.closeupList*Label.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.unitCloseup*info.width:  		500",
"xtconq.unitCloseup*info.height: 		300",
"xtconq.unitCloseup*info*font:		7x13",
"xtconq.unitCloseup*icon.height:		20",
"xtconq.unitCloseup*label.height:		20",
"xtconq.unitCloseup*flag.height:		20",
"xtconq.unitCloseup*side.height:		20",
"xtconq.unitCloseup*Label.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.unitCloseup*Command.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.unitCloseup*update.label:		Update",
"xtconq.unitCloseup*focus.label:		Focus",
"xtconq.unitCloseup*close.label:		Close",
"xtconq.sideCloseup*info.width:  			500",
"xtconq.sideCloseup*info.height:	 		150",
"xtconq.sideCloseup*info*font:			7x13",
"xtconq.sideCloseup*flag.height:			20",
"xtconq.sideCloseup*side.height:			20",
"xtconq.sideCloseup*Label.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.sideCloseup*Command.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.sideCloseup*update.label:			Update",
"xtconq.sideCloseup*close.label:			Close",
"xtconq.sideCloseup*filter.width: 		500",
"xtconq.sideCloseup*filter.Toggle.height:		20",
"xtconq.sideCloseup*filter.Label.height:		20",
"xtconq.sideCloseup*filter.label.label:		Filter units:",
"xtconq.sideCloseup*filter.allTypes.label:	all types",
"xtconq.sideCloseup*filter.acpLeft.label:		ACP left",
"xtconq.sideCloseup*listUnits.label:		list units",
"xtconq.unitList*Label.height:			20",
"xtconq.unitList*allTypes.label:			all types",
"xtconq.unitList*acpLeft.label:			ACP left",
"xtconq.unitList*failed.label:			\
no unit found matching filter criteria",
"xtconq.unitList*list.forceColumns:		true",
"xtconq.unitList*list.defaultColumns:		1",
"xtconq.unitList*port.height:			300",
"xtconq.unitList*port.width:			550",
"xtconq.unitList*Label.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.unitList*Command.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.closeupList.title:			xtconq closeup list",
"xtconq.closeupList.iconName:			xtconq closeup list",
"xtconq.closeupList*list.forceColumns:		true",
"xtconq.closeupList*list.defaultColumns:		1",
"xtconq.closeupList*port.height:			300",
"xtconq.closeupList*port.width:			550",
"xtconq.closeupList*Label.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.orders.title:				xtconq standing orders",
"xtconq.orders*port.height:			250",
"xtconq.orders*port.width:			449",
"xtconq.orders.form.?.font:	-adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.orders*orders.Form.vertDistance:		-1",
"xtconq.orders*orders.Form.horizDistance:		-1",
"xtconq.orders*orders.Form.?.height:		20",
"xtconq.orders*orders.Form.toggle.width:		20",
"xtconq.orders*orders.Form.width:			438",
"xtconq.orders*orders.Form.height:		30",
"xtconq.utypeSelect*box.width:			156",
"xtconq.utypeSelect*box.Command.height:		20",
"xtconq.utypeSelect*box.cancel.font: -adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.condSelect*box.Command.font: -adobe-helvetica-medium-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.condSelect*box.cancel.font: -adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.taskSelect.box.width:			200",
"xtconq.taskSelect*box.Command.font: -adobe-helvetica-medium-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.taskSelect*box.cancel.font: -adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq.stringSelect*baseTranslations: #override \
	<Key>Return: DoneStringSelect()",
"xtconq*ordersHelp.title:			xtconq standing orders help",
"xtconq*ordersHelp*Command.font:  -adobe-helvetica-bold-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*ordersHelp*Label.font:    -adobe-helvetica-medium-r-*-*-12-*-*-*-*-*-*-*",
"xtconq*ordersHelp*baseTranslations: #override \
	<Key>Return: DoneOrdersHelp() \\n\
	<Key>Escape: DoneOrdersHelp() ",
