.TH IMF2IMF 1 
.SH NAME
imf2imf \- manipulate Xconq image families
.SH SYNOPSIS
.B imf2imf
.I [ options ] ...
.SH DESCRIPTION
.PP
.B imf2imf
reads and writes
.I Xconq
image families.
[include some examples of usage]
.LP
Options:
.TP 5
.B \-i \idir\fP
sets the input directory.
.TP 5
.B \-o \idir\fP
sets the input directory.
.TP 5
.B \-p
enables progress display.
.TP 5
.B \--explode
writes out multiple imf files, one for each image family.
.TP 5
.B \--help
displays help information.
.SH SEE ALSO
.BR xconq (6), x2imf (1), imf2x (1)
.SH AUTHOR
Stan Shebs (shebs@cygnus.com)
