name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y libncurses-dev libsdl2-dev libxmu-dev
    - name: configure
      run: cmake -B build
    - name: build
      run: cmake --build build -j$(nproc)
    - name: test
      run: ctest --test-dir build --output-on-failure --label-exclude long
