name: C/C++ CI

on:
  push:
    branches: [ "pipeline" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install tools
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends autoconf automake g++ gcc libsdl1.2-dev libxmu-dev libxaw7-dev make tcl-dev tk-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
